
day1: day1.cpp
	g++ -std=c++14 -static day1.cpp -L../stringx/lib -lstringx -o bin/day1

day2: day2.cpp
	g++ -std=c++14 -static day2.cpp -L../stringx/lib -lstringx -o bin/day2

day3: day3.cpp
	g++ -std=c++14 -static day3.cpp -L../stringx/lib -lstringx -o bin/day3

day4: day4.cpp
	g++ -std=c++14 -static day4.cpp -L../stringx/lib -lstringx -o bin/day4
	
clean:
	rm -Rf bin/* || true
