
	
day1: day1.cpp
	g++ -std=c++14 day1.cpp -o bin/day1

day2: day2.cpp
	g++ -std=c++14 day2.cpp -o bin/day2

day3: day3.cpp
	g++ -std=c++14 day3.cpp -o bin/day3

day4: day4.cpp
	g++ -std=c++14 day4.cpp -o bin/day4
	
clean:
	rm -Rf bin/* || true
